server:
  # 端口号
  port: 80

spring:
  servlet:
    multipart:
      #单次上传 单文件大小
      max-file-size: 100GB
      #单次请求大小
      max-request-size: 100GB
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    # 数据库ip和数据库名称
    url: jdbc:mysql://127.0.0.1:3306/network_disk
    # 数据库账号
    username: root
    # 数据库密码
    password: 1234

project:
  # 文件储存地址
  path: D:\network-disk
  # 文件上传目录
  uploadPath: upload
  # 文件下载的目录
  downloadPath: download
  # 文件图标的目录
  imagesPath: images
  # 被删除文件的目录
  deletePath: delete
  # 上传服务开关
  uploadService: true
  # 下载服务开关
  downloadService: true
  # 公告内容
  announcement: 公告内容
  # 在线预览一次传输大小 MB
  size: 5

logging:
  file:
    # 输出的log文件名
    name: slf4j-log
    # 输出的文件的路径
    path: ./logs
    # 限制日志文件的大小
    max-size: 10MB
    # 日志的保存天数
    max-history: 7
  level:
    # 输出级别
    root: info
#  config: classpath:/config/logback-spring.xml


