spring:
  servlet:
    multipart:
      # 单次上传 总文件大小
      max-request-size: 200GB
      #单次上传 单文件大小
      max-file-size: 100GB
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/network_disk
    username: root
    password: 1234

project-file-path:
  # 文件上传到哪里
  upload: D:\network-disk
  # 文件下载的目录
  download: D:\network-disk
  # 文件图标的目录
  images: D:\network-disk-img
  # 被删除文件的目录
  delete: D:\network-disk-delete


logging:
  file:
    # 输出的log文件名
    name: slf4j-log
    # 输出的文件的路径
    path: ./logs
    # 限制日志文件的大小
    max-size: 10MB
    # 日志的保存天数
    max-history: 7
  level:
    # 输出级别
    root: info

server:
  # 端口号
  port: 80

fileServer:
  # 是否开启上传
  upload: true
  # 是否开启下载
  download: true

setAnnouncement: 公告内容